###
POST http://localhost:3000/users/login
Content-type: application/json

{
    "email":"piter@gemail.com",
    "password":"pa$$w0rd"
}

###
GET http://localhost:3000/users/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBpdGVyQGdlbWFpbC5jb20iLCJpYXQiOjE2NjgyMzI1OTl9.qJx5CJfxJPg7KVCOujOeyTrKhS2D54N9OzY6GjJwTKc


###
POST http://localhost:3000/users/register
Content-type: application/json

{
    "name":"Piter",
    "email":"piter@gemail.com",
    "password":"pa$$w0rd"
}

