###
POST http://localhost:3000/users/login
Content-type: application/json

{
    "email":"piter@gemail.com",
    "password":"pa$$w0rd1"
}

###
POST http://localhost:3000/users/register
Content-type: application/json

{
    "name":"Piter",
    "email":"piter@gemail.com",
    "password":"pa$$w0rd"
}

