###
POST http://localhost:3000/users/login
Content-type: application/json

{
    "email":"email@email.com",
    "password":"pa$$w0rd"
}

###
POST http://localhost:3000/users/register
Content-type: application/json

{
    "name":"John",
    "email":"john@gemail.com",
    "password":"pa$$w0rd"
}

